version: 0.0
os: linux

# Copy everything from the bundle into /opt/myapp (adjust to your app path)
files:
  - source: /
    destination: /opt/myapp
    overwrite: true

# Optional: fix ownership/permissions after files land
permissions:
  - object: /opt/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
  - object: /opt/myapp
    pattern: "**/"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 900
      runas: root

  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: ec2-user


